---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_jaas.conf
    volumes:
      - ./sasl-ssl-scram/secrets/zookeeper_jaas.conf:/etc/kafka/secrets/zookeeper_jaas.conf:ro

  # config-zookeeper:
  #   image: confluentinc/cp-kafka:7.5.0
  #   container_name: "config-zookeeper"
  #   depends_on:
  #     - zookeeper
  #   command: "bash -c 'echo Waiting for Zookeeper to be ready... && \
  #                         cub zk-ready zookeeper:22181 120 && \
  #                         kafka-configs --zookeeper zookeeper:22181 --alter --add-config 'SCRAM-SHA-256=[iterations=4096,password=Ohmidas@123]' --entity-type users --entity-name admin && \
  #                         kafka-configs --zookeeper zookeeper:22181 --alter --add-config 'SCRAM-SHA-256=[iterations=4096,password=Ohmidas@123]' --entity-type users --entity-name kafkaui && \
  #                         kafka-configs --zookeeper zookeeper:22181 --alter --add-config 'SCRAM-SHA-256=[iterations=4096,password=Ohmidas@123]' --entity-type users --entity-name client '"
  #   environment:
  #     KAFKA_BROKER_ID: ignored
  #     KAFKA_ZOOKEEPER_CONNECT: ignored
  #     KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_jaas_client.conf
  #   volumes:
  #     - ./sasl-ssl-scram/secrets/zookeeper_jaas_client.conf:/etc/kafka/secrets/zookeeper_jaas_client.conf

  broker1:
    image: confluentinc/cp-kafka:7.5.0
    hostname: broker1
    container_name: broker1
    depends_on:
      - zookeeper
    expose:
      - 9101
      - 9092
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: "r1"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_SSL:SASL_SSL,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://broker1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: credentials
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: credentials
      KAFKA_SSL_KEY_CREDENTIALS: credentials
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_jaas.conf
      KAFKA_SUPER_USERS: 'User:kafkaui'
      # enables 2-way authentication
      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=broker1 -Dcom.sun.management.jmxremote.rmi.port=9101
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
    volumes:
      - ./sasl-ssl-scram/secrets/kafka_jaas.conf:/etc/kafka/secrets/kafka_jaas.conf:ro
      - ./sasl-ssl-scram/secrets/credentials:/etc/kafka/secrets/credentials:ro
      - ./sasl-ssl-scram/secrets/kafka.truststore.jks:/etc/kafka/secrets/kafka.truststore.jks:ro
      - ./sasl-ssl-scram/secrets/broker1.server.keystore.jks:/etc/kafka/secrets/kafka.keystore.jks:ro
      - ./sasl-ssl-scram/secrets/client.properties:/home/appuser/client.properties:ro

  # kafka-ui:
  #   image: provectuslabs/kafka-ui:master
  #   container_name: kafka-ui
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - broker1
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local  
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker1:29092
  #     KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
  #     KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
  #     KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="kafkaui" password="Ohmidas@123";'
  #     KAFKA_CLUSTERS_0_SSL_TRUSTSTORELOCATION: /kafka.truststore.jks
  #     KAFKA_CLUSTERS_0_SSL_TRUSTSTOREPASSWORD: Ohmidas@123
  #   volumes:
  #     - ./sasl-ssl-scram/secrets/kafka.truststore.jks:/kafka.truststore.jks:ro
