apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-local
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.156-192.168.1.159
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system