apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pg
  labels:
    traefik.tcp.routers: "pg"
spec:
  entryPoints:
    - pg
  routes:
    - match: HostSNI(`*`)
      services:
        - name: postgresql-ha-pgpool
          namespace: postgres
          port: 5432