---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k3s-ohmidasvn-dev
spec:
  secretName: k3s-ohmidasvn-dev-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.k3s.ohmidasvn.dev"
  dnsNames:
  - "k3s.ohmidasvn.dev"
  - "*.k3s.ohmidasvn.dev"